version: '3.8'

services:
  ruleManagerPostgres:
    image: postgres:latest
    ports:
      - "5434:5434"
    env_file:
      - .env

  rulesManager:
    image: rulesmanagerapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - ruleManagerPostgres
    env_file:
      - .env

volumes:
  postgres_data: