version: '3.8'

services:
  postgres:
    image: postgres:latest
    ports:
      - "5435:5432"
    env_file:
      - .env

  spring-app:
    image: printscriptservice
    ports:
      - "8082:8080"
    depends_on:
      - postgres
    env_file:
      - .env
    platform: linux/amd64

volumes:
  postgres_data: